create table if not exists plans (
 id bigint generated by default as identity primary key,
 name text not null,
 room_limit integer,
 duration_days integer not null default 30,
 active boolean not null default true,
 created_at timestamptz default now()
);
create table if not exists keys (
 id bigint generated by default as identity primary key,
 key text unique not null,
 plan_id bigint references plans(id),
 active boolean not null default true,
 uses integer not null default 0,
 expires_at timestamptz,
 created_at timestamptz default now()
);
create table if not exists guilds (
 guild_id text primary key,
 name text,
 owner_id text,
 created_at timestamptz default now()
);
create table if not exists guild_config (
 guild_id text primary key,
 room_role_id text,
 notify_channel_id text,
 expiry_warning text
);
alter table guild_config add column if not exists expiry_warning text;
create table if not exists guild_keys (
 id bigint generated by default as identity primary key,
 guild_id text not null,
 key_id bigint references keys(id),
 active boolean not null default true,
 created_at timestamptz default now()
);
create table if not exists room_usage (
 id bigint generated by default as identity primary key,
 guild_id text not null,
 key_id bigint references keys(id),
 count integer not null default 0,
 unique(guild_id,key_id)
);
create table if not exists broadcasts (
 id bigint generated by default as identity primary key,
 message text not null,
 sent boolean not null default false,
 created_at timestamptz default now()
);
insert into plans(name,room_limit,duration_days)
select 'Semanal',20,7 where not exists(select 1 from plans where name='Semanal');
insert into plans(name,room_limit,duration_days)
select 'Mensal',100,30 where not exists(select 1 from plans where name='Mensal');

create table if not exists api_events (
 id bigint generated by default as identity primary key,
 event_id text unique not null,
 event_type text not null check (event_type in ('venda','cargo')),
 payload jsonb not null,
 received_at timestamptz not null default now(),
 created_at timestamptz not null default now()
);

create index if not exists api_events_type_idx on api_events(event_type);
create index if not exists api_events_received_at_idx on api_events(received_at desc);
